tap "homebrew/bundle"
tap "homebrew/core"

# brew
brew "bat"
brew "glib"
brew "python@3.9"
brew "cmake"
brew "cloc"
brew "exa"
brew "fd"
brew "fzf"
brew "gcc"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "jq"
brew "nvm"
brew "opam"
brew "ripgrep"
brew "rlwrap"
brew "tree"
brew "wget"
brew "z"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# cask
cask 'google-japanese-ime'
cask 'google-chrome'
cask 'visual-studio-code'
cask "rectangle"
cask "todoist"
cask "slack"
cask "logi-options-plus"
cask "karabiner-elements"
cask "tailscale"
