tap "homebrew/bundle"
tap "homebrew/core"

# brew
brew "bat"
brew "glib"
brew "python@3.9"
brew "cmake"
brew "exa"
brew "fd"
brew "fzf"
brew "gcc"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "jq"
brew "nvm"
brew "opam"
brew "pyenv"
brew "ripgrep"
brew "rlwrap"
brew "tree"
brew "wget"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# cask
cask 'alfred'
cask 'clipy'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'visual-studio-code'
cask "google-cloud-sdk"
